Algoritmo "custodoprotudo"
// Disciplina   : PA
// Professor   : Edilma
// Descrição   : 1 C/ turma B
// Autor(a)    :Pedro Carneiro Santos
// Data atual  : 09/03/2023
Var
nome : caractere
custo, valor: real

Inicio
// entrada
escreval (" digite o nome do produto: ")
leia (nome)
escreval ("digite o custo do produto: ")
leia (custo)

//processamento
valor <- custo+ 65/100* custo

//saida
escreval(" o valor do", nome," é :", valor)

Fimalgoritmo