Algoritmo "Dolar e real"
// Disciplina   : PA
// Professor   : Edilma
// Descrição   : 1 C/ turma B
// Autor(a)    :Pedro Carneiro Santos
// Data atual  : 09/03/2023
Var
RS, USS, conversao : real

Inicio
// entrada
escreval ("digite o valor do dolar em relação ao real: ")
leia (USS)
escreval ("digite o valor dos reais que serão convertidos: ")
leia (RS)


//processamento
conversao <- RS * USS

//saida
escreval(" A conversão do real é de :", conversao)

Fimalgoritmo