Algoritmo "média de combustivel"
// Disciplina   : PA
// Professor   : Edilma
// Descrição   : 1 C/ turma B
// Autor(a)    :Pedro Carneiro Santos
// Data atual  : 09/03/2023
Var
media, kilometros, combustivel: real

Inicio
// entrada
escreval (" digite os km percorridos: ")
leia (kilometros)
escreval ("digite o combustivel: ")
leia (combustivel)

//processamento
media <- kilometros/combustivel

//saida
escreval(" a média de combustivel foi", media)

Fimalgoritmo